version: '3.8'

services:
  ghost-db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: ghost-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./ghost-db:/var/lib/mysql
    networks:
      - ghost-net

  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    container_name: ghost
    depends_on:
      - ghost-db
    ports:
      - 2368:2368
    volumes:
      - ./ghost-content:/var/lib/ghost/content
    environment:
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
    networks:
      - ghost-net

networks:
  ghost-net:
    driver: bridge
